language: rust

rust:
    - stable
    - nightly

script:
    - cargo doc --no-deps
    - cargo build -v
    - cargo test -v

sudo: true

after_success: |
    [ $TRAVIS_BRANCH = master ] &&
    [ $TRAVIS_PULL_REQUEST = false ] &&
    ./publish.sh
