language: rust

rust:
    - stable
    - beta
    - nightly

script:
    - cargo doc --no-deps -p amethyst -p amethyst_engine -p amethyst_ecs
    - cargo build -v
    - cargo test -p amethyst -p amethyst_engine -p amethyst_ecs -v

sudo: true

after_success: |
    [ $TRAVIS_BRANCH = master ] &&
    [ $TRAVIS_PULL_REQUEST = false ] &&
    ./publish.sh
