# Set up the Rust toolchain.
language: rust
rust:
    - stable
    - beta
    - nightly

# Since this build doesn't require sudo, we can turn it off and improve build
# performance.
sudo: false

# Force third-party crates to persist from previous builds and update only when
# needed.
cache: cargo

# Install the necessary crates for building and testing the engine.
before_script:
    - export PATH=$PATH:/home/travis/.cargo/bin
    - (cargo install cargo-local-pkgs || true)
    - (cargo install rustfmt || true)

script: |
      cargo fmt -- --write-mode=diff &&
      cargo doc --no-deps -p amethyst -p amethyst_config -p amethyst_context -p amethyst_ecs -p amethyst_renderer &&
      cargo build -v &&
      cargo local-pkgs test -v

# Push notifications to `amethyst/general` and `amethyst/engine` Gitter chats.
notifications:
    webhooks:
        urls:
            - https://webhooks.gitter.im/e/9735c01977c1df3de5cb
