[package]
name = "amethyst"
version = "0.1.0"
authors = ["Eyal Kalderon <ebkalderon@gmail.com>"]
description = """
Data-oriented game engine written in Rust. This project is a work in progress and is very incomplete. Pardon our dust!
"""
keywords = ["game", "engine", "sdk", "amethyst"]

documentation = "http://ebkalderon.github.io/amethyst/doc/amethyst/"
homepage = "http://ebkalderon.github.io/amethyst/"
repository = "https://github.com/ebkalderon/amethyst"

readme = "README.md"
license = "MIT"

[lib]
name = "amethyst"
path = "src/lib.rs"

[dependencies]
threadpool = "0.1.4"
time = "0.1"
