[package]
name = "amethyst"
version = "0.3.0"
authors = ["Eyal Kalderon <ebkalderon@gmail.com>"]
description = "Data-oriented game engine written in Rust"
keywords = ["game", "engine", "sdk", "amethyst"]

documentation = "https://www.amethyst.rs/doc/amethyst"
homepage = "https://www.amethyst.rs/"
repository = "https://github.com/amethyst/amethyst"

readme = "README.md"
license = "MIT"

[dependencies]
time = "0.1"

[dependencies.amethyst_ecs]
path = "src/ecs/"
version = "0.1.0"

[dependencies.amethyst_renderer]
path = "src/renderer/"
version = "0.3.0"
