[package]
name = "amethyst_engine"
version = "0.1.4"
authors = ["Eyal Kalderon <ebkalderon@gmail.com>"]
description = "Core engine library"

documentation = "http://ebkalderon.github.io/amethyst/doc/amethyst/"
homepage = "http://ebkalderon.github.io/amethyst/"
repository = "https://github.com/ebkalderon/amethyst"

readme = "README.md"
license = "MIT"

[lib]
name = "amethyst_engine"
path = "src/lib.rs"

[dependencies]
threadpool = "0.1.4"
time = "0.1"
