[package]
name = "amethyst_engine"
version = "0.2.1"
authors = ["Eyal Kalderon <ebkalderon@gmail.com>"]
description = "Core engine library"
keywords = ["game", "engine", "core", "amethyst"]

documentation = "http://ebkalderon.github.io/amethyst/doc/amethyst/"
homepage = "http://ebkalderon.github.io/amethyst/"
repository = "https://github.com/ebkalderon/amethyst"

license = "MIT"

[lib]
name = "amethyst_engine"
path = "src/lib.rs"

[dependencies]
threadpool = "0.1.4"
time = "0.1"
