[package]
name = "amethyst_ui"
version = "0.1.0"
authors = ["Jacob Kiesel <kieseljake@gmail.com>"]

[dependencies]
amethyst_assets = { path = "../amethyst_assets", version = "0.2"}
amethyst_renderer = { path = "../amethyst_renderer", version = "0.5"}
specs = "0.10"
