[package]
name = "amethyst_ui"
version = "0.1.0"
authors = ["Jacob Kiesel <kieseljake@gmail.com>"]

[dependencies]
amethyst_assets = { path = "../amethyst_assets", version = "0.2"}
amethyst_core = { path = "../amethyst_core", version = "0.1"}
amethyst_renderer = { path = "../amethyst_renderer", version = "0.5"}
cgmath = { version = "0.14", features = ["eders"] }
gfx = { version = "0.16", features = ["cgmath-types", "serialize"] }
hibitset = "0.3"
rayon = "0.8"
rusttype = "0.2"
specs = "0.10"
unicode-normalization = "0.1"
