title: "Amethyst game"

logging:
    file_path: "new_project"
    output_level: "warn"
    logging_level: "debug"

display: extern
inner:
  inner_inner:
    field: 1823

inner_inner: extern