[package]
name = "amethyst_renderer"
version = "0.3.1"
authors = ["Eyal Kalderon <ebkalderon@gmail.com>"]
description = "High-level rendering engine with multiple backends"
keywords = ["game", "engine", "renderer", "3d", "amethyst"]

documentation = "https://www.amethyst.rs/doc/amethyst/"
homepage = "https://www.amethyst.rs/"
repository = "https://github.com/amethyst/amethyst"

readme = "README.md"
license = "MIT OR Apache-2.0"

[dependencies]
cgmath = "0.11"
gfx = "0.12"
gfx_core = "0.4"
gfx_device_gl = "0.11"
gfx_window_glutin = "0.12"
glutin = "0.6"
mopa = "0.2"

[dev-dependencies]
genmesh = "0.4"
rand = "0.3"

[dependencies.amethyst_ecs]
path = "../ecs/"
version = "0.1.0"
