[package]
name = "amethyst_renderer"
version = "0.2.0"
authors = ["Eyal Kalderon <ebkalderon@gmail.com>"]
description = "High-level rendering engine with multiple backends"

documentation = "http://ebkalderon.github.io/amethyst/doc/amethyst/"
homepage = "http://ebkalderon.github.io/amethyst/"
repository = "https://github.com/ebkalderon/amethyst"

readme = "README.md"
license = "MIT"

[dependencies]
gfx = "*"
